name: Data Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: python preprocessing/automate_Sofi-Zamzanah.py

      - name: Upload hasil preprocessing
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: preprocessing/dataset/
